{"uuid": "d7049859-3f9c-4bc3-a78c-629eb90793e1", "children": ["e49637f0-fa54-4602-ac5d-c35f9c29af1c"], "befores": [{"name": "capture_failure_screenshot", "status": "passed", "start": 1748582208766, "stop": 1748582208766}], "afters": [{"name": "capture_failure_screenshot::0", "status": "broken", "statusDetails": {"message": "AttributeError: 'Function' object has no attribute 'rep_call'\n", "trace": "  File \"/Users/anashuhada/PycharmProjects/SeleniumWithPython/.venv/lib/python3.13/site-packages/allure_commons/_allure.py\", line 231, in __call__\n    return self._fixture_function(*args, **kwargs)\n           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^\n  File \"/Users/anashuhada/PycharmProjects/SeleniumWithPython/.venv/lib/python3.13/site-packages/_pytest/fixtures.py\", line 907, in _teardown_yield_fixture\n    next(it)\n    ~~~~^^^^\n  File \"/Users/anashuhada/PycharmProjects/SeleniumWithPython/tutorialsninja/conftest.py\", line 32, in capture_failure_screenshot\n    if request.node.rep_call.failed:\n       ^^^^^^^^^^^^^^^^^^^^^\n"}, "start": 1748582213567, "stop": 1748582213567}], "start": 1748582208766, "stop": 1748582213567}