{"uuid": "1aae3c95-5e27-4c44-bd0d-8ddb5a0a00bf", "children": ["52e0cd9f-7e25-495a-bccd-d5a012b2c674"], "befores": [{"name": "capture_failure_screenshot", "status": "passed", "start": 1748581566594, "stop": 1748581566594}], "afters": [{"name": "capture_failure_screenshot::0", "status": "broken", "statusDetails": {"message": "AttributeError: 'Function' object has no attribute 'rep_call'\n", "trace": "  File \"/Users/anashuhada/PycharmProjects/SeleniumWithPython/.venv/lib/python3.13/site-packages/allure_commons/_allure.py\", line 231, in __call__\n    return self._fixture_function(*args, **kwargs)\n           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^\n  File \"/Users/anashuhada/PycharmProjects/SeleniumWithPython/.venv/lib/python3.13/site-packages/_pytest/fixtures.py\", line 907, in _teardown_yield_fixture\n    next(it)\n    ~~~~^^^^\n  File \"/Users/anashuhada/PycharmProjects/SeleniumWithPython/tutorialsninja/conftest.py\", line 32, in capture_failure_screenshot\n    if request.node.rep_call.failed:\n       ^^^^^^^^^^^^^^^^^^^^^\n"}, "start": 1748581571388, "stop": 1748581571389}], "start": 1748581566594, "stop": 1748581571389}