{"uuid": "4c1d9480-ae19-4124-8638-25ca935e095c", "children": ["4b246d25-e7f4-49d6-ae4d-eaa118128eb4"], "befores": [{"name": "capture_failure_screenshot", "status": "passed", "start": 1748581581068, "stop": 1748581581068}], "afters": [{"name": "capture_failure_screenshot::0", "status": "broken", "statusDetails": {"message": "AttributeError: 'Function' object has no attribute 'rep_call'\n", "trace": "  File \"/Users/anashuhada/PycharmProjects/SeleniumWithPython/.venv/lib/python3.13/site-packages/allure_commons/_allure.py\", line 231, in __call__\n    return self._fixture_function(*args, **kwargs)\n           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^\n  File \"/Users/anashuhada/PycharmProjects/SeleniumWithPython/.venv/lib/python3.13/site-packages/_pytest/fixtures.py\", line 907, in _teardown_yield_fixture\n    next(it)\n    ~~~~^^^^\n  File \"/Users/anashuhada/PycharmProjects/SeleniumWithPython/tutorialsninja/conftest.py\", line 32, in capture_failure_screenshot\n    if request.node.rep_call.failed:\n       ^^^^^^^^^^^^^^^^^^^^^\n"}, "start": 1748581585941, "stop": 1748581585942}], "start": 1748581581068, "stop": 1748581585942}